# Generated by Django 4.2.11 on 2024-03-15 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_id', models.IntegerField()),
                ('certificate_file', models.FileField(upload_to='certificates/')),
            ],
        ),
    ]
